In [1]:
import json

import pandas as pd

In [5]:
# Read the json file

f = open('samples.json',)

In [6]:
# import json file

data = json.load(f)

In [4]:
# Creating empty lists

otu_id_temp = []

sample_values_temp = []

otu_labels_temp = []

In [5]:
for i in range(len(data['names'])):
    
    # Extract values from dictionary
    
    otu_id_extract = data['samples'][i]['otu_ids']
    
    sample_values_extract = data['samples'][i]['sample_values']
    
    otu_labels_extract =  data['samples'][i]["otu_labels"]
    
    # Appending to the empty list
    
    otu_id_temp.append(otu_id_extract)
    
    sample_values_temp.append(sample_values_extract)
    
    otu_labels_temp.append(otu_labels_extract)

In [6]:
# Concatenate them into a single list

otu_id_list = [item for sublist in otu_id_temp for item in sublist]

sample_values_list = [item for sublist in sample_values_temp for item in sublist]

otu_labels_list = [item for sublist in otu_labels_temp for item in sublist]

In [7]:
# Create a DF and extract top 10

Combine_df = pd.DataFrame(
    {'OTU_ID': otu_id_list,
     'Sample_Values': sample_values_list,
     'OTU_labels': otu_labels_list
    })

In [8]:
Top_ten_df = Combine_df.head(10)

Top_ten_df

   OTU_ID  Sample_Values                                         OTU_labels
0    1167          163.0  Bacteria;Bacteroidetes;Bacteroidia;Bacteroidal...
1    2859          126.0  Bacteria;Firmicutes;Clostridia;Clostridiales;I...
2     482          113.0                                           Bacteria
3    2264           78.0  Bacteria;Firmicutes;Clostridia;Clostridiales;I...
4      41           71.0                                           Bacteria
5    1189           51.0  Bacteria;Bacteroidetes;Bacteroidia;Bacteroidal...
6     352           50.0                                           Bacteria
7     189           47.0                                           Bacteria
8    2318           40.0  Bacteria;Firmicutes;Clostridia;Clostridiales;I...
9    1977           40.0       Bacteria;Firmicutes;Clostridia;Clostridiales

In [9]:
labels = Top_ten_df['OTU_labels'].to_list()

ID = Top_ten_df['OTU_ID'].to_list()

values = Top_ten_df['Sample_Values'].to_list()

In [10]:
ID

[1167, 2859, 482, 2264, 41, 1189, 352, 189, 2318, 1977]

In [11]:
values

[163.0, 126.0, 113.0, 78.0, 71.0, 51.0, 50.0, 47.0, 40.0, 40.0]

In [13]:
labels

['Bacteria;Bacteroidetes;Bacteroidia;Bacteroidales;Porphyromonadaceae;Porphyromonas',
 'Bacteria;Firmicutes;Clostridia;Clostridiales;IncertaeSedisXI;Peptoniphilus',
 'Bacteria',
 'Bacteria;Firmicutes;Clostridia;Clostridiales;IncertaeSedisXI',
 'Bacteria',
 'Bacteria;Bacteroidetes;Bacteroidia;Bacteroidales;Porphyromonadaceae;Porphyromonas',
 'Bacteria',
 'Bacteria',
 'Bacteria;Firmicutes;Clostridia;Clostridiales;IncertaeSedisXI;Anaerococcus',
 'Bacteria;Firmicutes;Clostridia;Clostridiales']

In [15]:
# Extracting a sample for bubble chart

sample_df = Combine_df.head(50)

sample_df

    OTU_ID  Sample_Values                                         OTU_labels
0     1167          163.0  Bacteria;Bacteroidetes;Bacteroidia;Bacteroidal...
1     2859          126.0  Bacteria;Firmicutes;Clostridia;Clostridiales;I...
2      482          113.0                                           Bacteria
3     2264           78.0  Bacteria;Firmicutes;Clostridia;Clostridiales;I...
4       41           71.0                                           Bacteria
5     1189           51.0  Bacteria;Bacteroidetes;Bacteroidia;Bacteroidal...
6      352           50.0                                           Bacteria
7      189           47.0                                           Bacteria
8     2318           40.0  Bacteria;Firmicutes;Clostridia;Clostridiales;I...
9     1977           40.0       Bacteria;Firmicutes;Clostridia;Clostridiales
10    3450           37.0  Bacteria;Proteobacteria;Epsilonproteobacteria;...
11     874           36.0  Bacteria;Actinobacteria;Actinobacteria;Actinom...
12    1959           30.0                     Bacteria;Firmicutes;Clostridia
13    2191           28.0  Bacteria;Firmicutes;Clostridia;Clostridiales;I...
14    1950           25.0                     Bacteria;Firmicutes;Clostridia
15    2077           23.0       Bacteria;Firmicutes;Clostridia;Clostridiales
16    2275           22.0  Bacteria;Firmicutes;Clostridia;Clostridiales;I...
17     944           19.0  Bacteria;Actinobacteria;Actinobacteria;Actinom...
18    2184           19.0  Bacteria;Firmicutes;Clostridia;Clostridiales;I...
19    2244           14.0  Bacteria;Firmicutes;Clostridia;Clostridiales;I...
20    2024           13.0       Bacteria;Firmicutes;Clostridia;Clostridiales
21    2419           13.0  Bacteria;Firmicutes;Clostridia;Clostridiales;I...
22    2811           13.0  Bacteria;Firmicutes;Clostridia;Clostridiales;I...
23     165           12.0                                           Bacteria
24    2782           12.0  Bacteria;Firmicutes;Clostridia;Clostridiales;I...
25    2247           11.0  Bacteria;Firmicutes;Clostridia;Clostridiales;I...
26    2011           11.0       Bacteria;Firmicutes;Clostridia;Clostridiales
27    2396           11.0  Bacteria;Firmicutes;Clostridia;Clostridiales;I...
28     830           10.0  Bacteria;Actinobacteria;Actinobacteria;Actinom...
29    2964           10.0  Bacteria;Firmicutes;Clostridia;Clostridiales;V...
30    1795           10.0  Bacteria;Firmicutes;Bacilli;Bacillales;Staphyl...
31    2722            8.0  Bacteria;Firmicutes;Clostridia;Clostridiales;I...
32     307            7.0                                           Bacteria
33    2178            7.0       Bacteria;Firmicutes;Clostridia;Clostridiales
34    2908            7.0  Bacteria;Firmicutes;Clostridia;Clostridiales;P...
35    1193            6.0  Bacteria;Bacteroidetes;Bacteroidia;Bacteroidal...
36    2167            5.0       Bacteria;Firmicutes;Clostridia;Clostridiales
37    1208            5.0  Bacteria;Bacteroidetes;Bacteroidia;Bacteroidal...
38    2039            5.0       Bacteria;Firmicutes;Clostridia;Clostridiales
39    1274            4.0  Bacteria;Bacteroidetes;Bacteroidia;Bacteroidal...
40    2739            4.0  Bacteria;Firmicutes;Clostridia;Clostridiales;I...
41    2737            4.0  Bacteria;Firmicutes;Clostridia;Clostridiales;I...
42    1314            3.0  Bacteria;Bacteroidetes;Bacteroidia;Bacteroidal...
43    1962            3.0                     Bacteria;Firmicutes;Clostridia
44    2186            3.0  Bacteria;Firmicutes;Clostridia;Clostridiales;I...
45    2335            3.0  Bacteria;Firmicutes;Clostridia;Clostridiales;I...
46    2936            3.0  Bacteria;Firmicutes;Clostridia;Clostridiales;R...
47     907            3.0  Bacteria;Actinobacteria;Actinobacteria;Actinom...
48     833            3.0  Bacteria;Actinobacteria;Actinobacteria;Actinom...
49    2483            2.0  Bacteria;Firmicutes;Clostridia;Clostridiales;I...

In [16]:
sample_labels = sample_df['OTU_labels'].to_list()

sample_ID = sample_df['OTU_ID'].to_list()

sample_values = sample_df['Sample_Values'].to_list()

In [20]:
# file1 = 'otu_id_list.txt'

# file2 = 'otu_labels_list.txt'

# file3 = 'sample_values_list.txt'

# with open(file1, 'w') as text:

#     text.write('otu_id_list =' + str(sample_ID))
    
# with open(file2, 'w') as text:

#     text.write('otu_labels_list =' + str(sample_labels))
    
# with open(file3, 'w') as text:

#     text.write('sample_values_list =' + str(sample_values))

In [29]:
# Create the data.js file

meta = data['metadata']

names = data['names']

data2 = dict(zip(names, meta))

In [35]:
file4 = 'data.txt'

with open(file4, 'w') as text:

    text.write('var data = ' + str(data2))